[package]
name = "egui-theme-switch"
version = "0.1.0"
edition = "2021"
rust-version = "1.79.0"
license = "MIT OR Apache-2.0"
readme = "readme.md"
repository = "https://github.com/bash/egui-theme-switch"
description = "A pretty theme switch for your egui app"
keywords = ["egui", "widget", "dark-light", "switch"]
categories = ["gui"]
exclude = [".github", "doc/*.py", "deny.toml"]

[features]
default = ["accesskit"]
accesskit = ["egui/accesskit"]

[dependencies]
egui = { version = "0.28.1", default-features = false }

[workspace]
members = ["demo"]
