[graph]
all-features = true

[output]
feature-depth = 1

[licenses]
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "ISC",
    "LicenseRef-UFL-1.0",
    "MIT",
    "OFL-1.1",
    "Unicode-DFS-2016",
    "Zlib",
]
confidence-threshold = 1.0

[bans]
multiple-versions = "warn"
wildcards = "deny"
allow-wildcard-paths = true

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
