[graph]
all-features = true

[output]
feature-depth = 1

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "OFL-1.1",
    "LicenseRef-UFL-1.0",
    "Unicode-DFS-2016",
]
confidence-threshold = 1.0

[bans]
multiple-versions = "deny"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
