[graph]
all-features = true

[output]
feature-depth = 1

[licenses]
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "MIT",
]
confidence-threshold = 1.0

[bans]
multiple-versions = "warn"
wildcards = "deny"
allow-wildcard-paths = true

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
